dist: bionic
language: python

python:
 - '3.8'

addons:
 firefox: latest

install:
 - pip install -r requirements.txt

before_script:
 - install-webdrivers --./webdrivers/geckodriver

env:
 global:
   - DJANGO_SETTINGS_MODULE="p8.settings.travis"

services:
 - postgresql

script:
 - python manage.py test 