# Generated by Django 3.0.6 on 2020-06-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_searched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search', to='products.Products')),
                ('product_substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_substitute', to='products.Products')),
            ],
        ),
    ]
