# Generated by Django 3.0.6 on 2020-06-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_searched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search', to='products.Products')),
                ('product_substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_substitute', to='products.Products')),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favoris', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
