# Generated by Django 3.0.6 on 2020-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200524_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(related_name='products', to='products.Category'),
        ),
        migrations.DeleteModel(
            name='Cat_prod',
        ),
    ]
